baseURL = "https://genomicsxai.github.io/"
title = "Genomics X AI"
theme = "Stack"
enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  # Include blogs section in main sections for homepage
  mainSections = ["blogs", "post"]

[taxonomies]
  tag = "tags"                # scientific tags
  scope = "scope"                #other tags
  audience = "audience"
  lab = "labs"
  author = "authors"
  category = "categories"
